"""initial migration

Revision ID: 104dc78f5c89
Revises: None
Create Date: 2018-04-01 06:56:29.477000

"""

# revision identifiers, used by Alembic.
revision = '104dc78f5c89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
